### PR TITLE
Fix tag on failure test

### LINKED ISSUE #55: Fail test on 8.x because `un[sup]]ported` is considered valid json key
**Build scan**:
https://app.travis-ci.com/github/logstash-plugins/logstash-filter-json/jobs/613875477#L1419

**Repro line**:
```
export LOGSTASH_PATH=/Users/andrea/workspace/logstash_andsel/ && export LOGSTASH_SOURCE=1
export JRUBY_OPTS="-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -J--add-opens=java.base/java.security=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.nio.channels=ALL-UNNAMED -J--add-opens=java.base/sun.nio.ch=ALL-UNNAMED -J--add-opens=java.management/sun.management=ALL-UNNAMED -Xregexp.interruptible=true -Xcompile.invokedynamic=true -Xjit.threshold=0 -J-XX:+PrintCommandLineFlags -v -W1"
bundle install
bundle exec rspec
```
**Reproduces locally?**:
yes 

**Applicable branches**:
`main`

**Failure history**:

**Failure excerpt**:
```
Failures:

  1) LogStash::Filters::Json unsupported field name using `target` "{\"okay\":true, \"un[sup]]ported\": \"foo\", \"another\": \"..." processes events as specified
     Failure/Error: insist { subject.get("tags") }.include?("_jsonparsefailure")

     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/andrea/.rvm/gems/jruby-9.4.2.0/gems/insist-1.0.0/lib/insist/enumerables.rb:11:in `include?'
     # ./spec/filters/json_spec.rb:83:in `block in <main>'
     # /Users/andrea/.rvm/gems/jruby-9.4.2.0/gems/logstash-devutils-2.4.0-java/lib/logstash/devutils/rspec/spec_helper.rb:61:in `block in <main>'

Finished in 2.73 seconds (files took 2.07 seconds to load)
24 examples, 1 failure

Failed examples:

rspec ./spec/filters/json_spec.rb:80 # LogStash::Filters::Json unsupported field name using `target` "{\"okay\":true, \"un[sup]]ported\": \"foo\", \"another\": \"..." processes events as specified

Randomized with seed 39629
```

## Task to do after issue resolution
- [ ] Re-enable it in Logstash `ci/test_plugins.rb`

### PR DESCRIPTION
**Pull request by kaisecheng**
Field Reference can handle special characters in 8.3.0. This commit excludes the failed test from 8.3+

Related:
https://github.com/elastic/logstash/issues/11941

Close #55

### CODE REVIEW

**Comment by kaisecheng** [comment]
@logstashmachine bump patch

File: spec/filters/json_spec.rb [hunk 1]
```diff
@@ -62,8 +62,9 @@
   end
 
   logstash_version = Gem::Version.create(LOGSTASH_CORE_VERSION)
-
-  if (Gem::Requirement.create('>= 7.0').satisfied_by?(logstash_version) ||
+  
+  # Field Reference can handle special characters since 8.3.0
+  if ((Gem::Requirement.create('>= 7.0').satisfied_by?(logstash_version) && Gem::Requirement.create('< 8.3').satisfied_by?(logstash_version)) ||
```
Comment (mashhurs) [inline spec/filters/json_spec.rb:67]: Do we have or can we add test cases for 8.3+ LS versions?

Comment (kaisecheng) [reply spec/filters/json_spec.rb:67]: we have existing test for [tagging](https://github.com/logstash-plugins/logstash-filter-json/blob/fix_tag_on_failure_test/spec/filters/json_spec.rb#L59-L60) json fail for 8.3+

**Review by andsel — APPROVED** [review]
LGTM
